changelog:
	@if test -d "$(srcdir)/.git"; \
        then \
                echo Creating ChangeLog && \
                ( cd "$(top_srcdir)" && \
                  echo '# Generated by Makefile. Do not edit.'; echo; \
                  $(top_srcdir)/missing --run git log  \
                  --pretty=format:'commit:%n%ad  %an  <%ae>%ndescription:%n%s%n%bfiles:'\
                  --stat --name-only --date=short --after="$(GIT_LOG_START_DATE)" --topo-order) | \
                  $(top_srcdir)/common/gitlog2ChangeLog > ChangeLog.tmp \
                && echo "\n" >> ChangeLog.tmp \
                && cat $(top_srcdir)/ChangeLog.old >> ChangeLog.tmp \
                && cp -f ChangeLog.tmp $(distdir)/ChangeLog \
                || ( rm -f ChangeLog.tmp ; \
                     echo Failed to generate ChangeLog >&2 ); \
        else \
                echo A git clone is required to generate a ChangeLog >&2; \
        fi
