#!/usr/bin/awk -f
BEGIN {
commit_msg = ""
backport = ""
reviewed = ""
file_list = ""
in_files = 0
in_description = 0
in_commit = 0
}
/^commit:/ {
  in_files = 0
  in_commit = 1
  if (reviewed != "")
    print reviewed
  if (backport != "")
    print backport
  if (file_list != "")
    print file_list
  if (commit_msg != "")
    print commit_msg

  commit_msg = ""
  backport = ""
  reviewed = ""
  file_list = ""
  next
}
/^description:/ {
  in_description = 1
  in_commit = 0
  next
}
/^files:/ {
  in_description = 0
  in_files = 1
  next
}
in_commit == 1 {
  print sprintf("%s\n", $0)
  next
}
in_description == 1 {
  if ($0 ~ /^Backport/) {
    backport = sprintf("\t%s", $0)
    next
  }
  if ($0 ~ /^reviewed by/) {
    reviewed = sprintf("\t%s", $0)
    next
  }
  if (commit_msg == "")
    commit_msg = sprintf("\t%s\n", $0)
  else
    commit_msg = sprintf("%s\t%s\n", commit_msg, $0)
  next
}
in_files == 1 {
  if ($0 != "")
    if (file_list == "")
      if (reviewed || backport)
        file_list = sprintf("\n\t* %s:", $0)
      else
        file_list = sprintf("\t* %s:", $0)
    else
      file_list = sprintf("%s\n\t* %s:", file_list, $0)
  next
}
END {
  if (reviewed != "")
    print reviewed
  if (backport != "")
    print backport
  if (file_list != "")
    print file_list
  if (commit_msg != "")
    print commit_msg
}
